parameters:
#    php_objects_contract.example.class: EdouardKombo\PhpObjectsContractBundle\Example

services:
#    php_objects_contract.example:
#        class: %php_objects_contract.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
